# FIX: Changed to Chrome (more stable for local + CI use)
# Change back to Firefox if Firefox is your preference
browser=chrome

app.qa.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
app.qa.username=Admin
app.qa.password=admin123